# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=6, unique=True)),
                ('employeeName', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('belt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pi_app.Belt')),
            ],
        ),
    ]
